### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by cambiata** [ianharrigan/HaxeUILayoutPreview#1]
Hi Ian!
Trying, but get the error below when trying to open a xml in an HaxeUI project.
Using FD 5.0.0.5

Index 1 out of range
Parameter name: index
   vid System.Windows.Forms.Control.ControlCollection.get_Item(Int32 index)
   vid HaxeUILayoutPreview.TabDetails.GetMiniMap()
   vid HaxeUILayoutPreview.TabDetails.UpdatePreviews()
   vid HaxeUILayoutPreview.PluginMain.HandleEvent(Object sender, NotifyEvent e, HandlingPriority prority)
   vid PluginCore.Managers.EventManager.DispatchEvent(Object sender, NotifyEvent e)
![error](https://cloud.githubusercontent.com/assets/217074/7146494/26c93a18-e2f4-11e4-84ee-da3d35f0abd6.png)

**Comment by ianharrigan** [comment]
Ok, that (sort of) makes sense, the MiniMap stuff was bolted on - Added it as i dont think it needed to be there for layouts (they tend to be small), and there is no checking. When you dismiss that does it all work out?

And is there a minimap?

**Comment by cambiata** [comment]
Nope, I don't have minimap installed.

**Comment by ianharrigan** [comment]
right... that'll be it then... Can i ask a favour, can you give me 10 mins, let me tighten it up and you retest?

**Comment by ianharrigan** [comment]
(ill disabled minimap too, but a fresh test would be ideal)

**Comment by cambiata** [comment]
Sure!

**Comment by ianharrigan** [comment]
Can you try that now? I managed to reproduce it so im pretty sure its fixed, but if you could confirm that would be great.

**Comment by cambiata** [comment]
Will do!

**Comment by ianharrigan** [comment]
Cheers Jonas!

**Comment by cambiata** [comment]
Works! This is so cool..!

**Comment by ianharrigan** [comment]
Heh heh... Coool! Glad it worked... will close this now...

Its pretty fun eh? Any feed back more than welcome. 

Btw, there are resource hooks also, so you can (should be able) to use images, text, binary (ie, gifs, bmps, pngs, svgs) in your project and the preview will still work! 

Let me know if you find anything else!

PS: this is silly... :p
![haha](https://cloud.githubusercontent.com/assets/3024242/7147024/40f892d6-e2f8-11e4-95ed-2331e73c6281.png)
